### ISSUE TITLE
How to update when on replit?

### ISSUE THREAD

**Issue by expected-ingot** [TahaGorme/slashy#14]

**Comment by expected-ingot** [comment]
Also for some reason my accounts don't do anything, not even a "Logged on" message

**Comment by expected-ingot** [comment]
> Also for some reason my accounts don't do anything, not even a "Logged on" message

Turns out there was 429 or something
Also I found out that you can just change the version string in index.js

**Comment by kyan27a** [comment]
![image](https://user-images.githubusercontent.com/84374752/208768772-c69b942f-6d06-4554-bbb0-32aebfc9ed38.png)
 Use the Git option to pull the latest version
