### ISSUE TITLE
How to avoid getting banned when using this 24/7?

### ISSUE THREAD

**Issue by expected-ingot** [TahaGorme/slashy#15]
this has been running for 3 days now and I just got a email from Discord saying that i got banned for selfbotting and it was on my main... how do I avoid this for next time

**Comment by TahaGorme** [comment]
i have been running slashy since 2 months. 24/7 on 19 accounts. no ban

do not use slashy in public servers 
someone probably reported you
i never got banned for using slashy

try using slashy in the dms
846312267255644200 - use this as the channel id

**Comment by expected-ingot** [comment]
i do not use slashy in public servers, only a server i made for my alts only
i will try using it in dms
also i am sure that channel id is only for your accounts... not mine

**Comment by TahaGorme** [comment]
there may be an issue with your config then. but an issue with the config should get you banned from dank memer not discord. did you change the sleep or break delays?

**Comment by expected-ingot** [comment]
all i did is remove trivia (it kept saying "you already have a running command"), change a bit of the API and website code and ye
