### ISSUE TITLE
Make self bot stream a trending game

### ISSUE THREAD

**Issue by red78massive1573** [TahaGorme/slashy#21]
use shero or dank assistant to get trending game then stream the game and fall back to random game when there are none (no bot for telling the current trending game)

**Comment by kyan0045** [comment]
Don't think we'll be using an external bot, as we would have to host a intermediary API that every instance connects to. If you know of any API that does the same as these bots, or these bots's API's, please feel free to share.

**Comment by kyan0045** [comment]
Will be considered for v2 though ^
