### ISSUE TITLE
Make the script use less RAM

### ISSUE THREAD

**Issue by red78massive1573** [TahaGorme/slashy#22]
when using slashy in replit, it will reach 512 MB RAM limit. And the program will just stop doing anything. When running it for 5-10 seconds, it went fine. but it suddenly hit 512MB RAM and then no response (there are no errors)

**Comment by red78massive1573** [comment]
i am using the program with 3 alts (if this helps)

**Comment by kyan0045** [comment]
Ran it on 4 accounts using replit for 2 months, had no ram issues myself..

**Comment by red78massive1573** [comment]
idk then. but it seems that my ram is all used up

**Comment by TahaGorme** [comment]
The script uses less ram. I was able to use it on replit for 2 months with 18 accounts
