### ISSUE TITLE
Autobuy

### ISSUE THREAD

**Issue by SANKETOP** [TahaGorme/slashy#50]
Autobuy not working
Not autobuying shovel and rifle

**Comment by SANKETOP** [comment]
Oh but when it was maintained there was autobuy and today autobuy I think it's same

**Comment by SANKETOP** [comment]
> It changed when the shop was no longer /shop buy.

Oh

**Comment by SANKETOP** [comment]
Do u any other auto dank that has this feature?

**Comment by kyan0045** [comment]
Dank botting is practically dead
