### ISSUE TITLE
[Feature Request] Gambling Commands

### ISSUE THREAD

**Issue by Clumsy-Assassin** [TahaGorme/slashy#8]
Could you please add support for gambling commands(mainly for levelling), slots would be pretty easy to implement too, since it's just one command and no more button presses. The amount could be configured through the  json file, and can be altered by using a range, although that might not be necessary since many users also just spam the command by copy/paste for fast levelling.
Also, thanks for this wonderful bot!

**Comment by TahaGorme** [comment]
Yes sure. I already codes the scratch command but did not add it as i lost more money than what i earned. Also join the discord server for updates.
